CREATE DATABASE IF NOT EXISTS Users;
USE Users;

CREATE TABLE Usuario (
id BIGINT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(30) NOT NULL,
lastName VARCHAR(30) NOT NULL,
userName VARCHAR(30) NOT NULL,
password VARCHAR(30) NOT NULL,
email VARCHAR(30) NOT NULL,
birthday DATE NOT NULL,
balance INT DEFAULT 0
);

ALTER TABLE Usuario ADD id BIGINT PRIMARY KEY AUTO_INCREMENT;
ALTER TABLE Usuario ADD COLUMN balance INT DEFAULT 0;

CREATE TABLE games(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL,
genre VARCHAR(100) NOT NULL,
exePath VARCHAR(100) NOT NULL
);

CREATE TABLE GameSession(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
game_id BIGINT NOT NULL,
user_id BIGINT NOT NULL,
start_time DATETIME NOT NULL,
end_time DATETIME NOT NULL,
total_time INT NOT NULL,
FOREIGN KEY (game_id) REFERENCES games(id),
FOREIGN KEY (user_id) REFERENCES Usuario(id)
);


